spring.application.name=multitenant-electricity-management


spring.datasource.url=jdbc:postgresql://localhost:5432/demo_mutlitenant
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO

spring.flyway.enabled=false
spring.jpa.properties.hibernate.multiTenancy=SCHEMA