spring.application.name=multitenant-electricity-management

spring.datasource.url=jdbc:postgresql://localhost:5432/multitenant_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

logging.level.root=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.flyway.enabled=false
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

jwt.SECRET=${JWT_SECRET}
jwt.EXPIRATION=8640000

logging.level.org.springframework.security=DEBUG

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# default path: h2-console
spring.h2.console.path=/h2-ui